---
abstract: 'serializer for handling CBOR data'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Serializer-CBOR
no_index:
  directory:
    - t
    - inc
requires:
  Modern::Perl: 0
  Test::More: 0
resources:
  bugtracker: https://github.com/zurborg/libdancer-serializer-cbor-perl/issues
  homepage: https://metacpan.org/release/Dancer-Serializer-CBOR
  repository: https://github.com/zurborg/libdancer-serializer-cbor-perl.git
version: 0.100
