---
abstract: 'serializer for handling CBOR data'
author:
  - 'David Zurborg <zurborg@cpan.org>'
build_requires:
  Dancer: '0'
  Dancer::Test: '0'
  Module::Signature: '0'
  Socket: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.143240'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer-Serializer-CBOR
requires:
  CBOR::XS: '0'
  Carp: '0'
  Dancer::Exception: '0'
  Dancer::Serializer::Abstract: '0'
  base: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/zurborg/libdancer-serializer-cbor-perl/issues
  homepage: https://github.com/zurborg/libdancer-serializer-cbor-perl
  repository: https://github.com/zurborg/libdancer-serializer-cbor-perl.git
version: '0.101'
